### ISSUE TITLE
Can't create CDF from output of cdfepoch.compute

### ISSUE THREAD

**Issue by johncoxon** [MAVENSDC/cdflib#148]
I'm used to using `spacepy.pycdf` for creating CDFs, but `pycdf` is not currently compatible with Apple Silicon Macs so I'm using `cdflib` for the first time and coming across some issues.

In `pycdf` the way I would create a CDF with various outputs is like this:
```
import datetime as dt
import numpy as np
from spacepy import pycdf

time = np.array([dt.datetime(2001,1,1),
                 dt.datetime(2001,1,2),
                 dt.datetime(2001,1,3),
                 dt.datetime(2001,1,4),
                 dt.datetime(2001,1,5),
                 dt.datetime(2001,1,6),
                 dt.datetime(2001,1,7),
                 dt.datetime(2001,1,8),
                 dt.datetime(2001,1,9),
                 dt.datetime(2001,1,10)])

with pycdf.CDF(test.cdf, "") as f:
        f["time"] = time
        f["GEO_lat"] = np.arange(0, 90)
        f["GEO_lon"] = np.arange(0, 180)
```

In `cdflib` I'm trying to do the same thing like this:

```
import cdflib
import datetime as dt
import numpy as np

cdf = cdflib.cdfwrite.CDF("test.cdf")

var_spec = {}
var_spec['Variable'] = "time"
var_spec['Data_Type'] = "CDF_EPOCH"
var_spec['Num_Elements'] = 10
var_spec['Rec_Vary'] = True
var_spec['Dim_Sizes'] = []

time = np.array([dt.datetime(2001,1,1),
                 dt.datetime(2001,1,2),
                 dt.datetime(2001,1,3),
                 dt.datetime(2001,1,4),
                 dt.datetime(2001,1,5),
                 dt.datetime(2001,1,6),
                 dt.datetime(2001,1,7),
                 dt.datetime(2001,1,8),
                 dt.datetime(2001,1,9),
                 dt.datetime(2001,1,10)])

time_list = [[f.year, f.month, f.day, 0, 0, 0, 0] for f in time]
var_data = cdflib.cdfepoch.compute(time_list)

cdf.write_var(var_spec, var_data=var_data)
cdf.close()
```

When I run this I get the error `ValueError: Missing/invalid required spec for creating variable.` I've tried looking the docs for `write_var` up on readthedocs.io, but it doesn't explain what the acceptable inputs for the various mandatory inputs are, and because `pycdf` infers all that for you I'm not sure what I'm doing wrong.

I'd like to ask for some concrete examples of what the required inputs are for the various variables to be put into the documentation, and for the error message that's output to be more descriptive about which part of the `var_spec` object is malformed, as it would be nice to be able to know which of the 5 keys are the problem.

**Comment by dstansby** [comment]
I've improved this in https://github.com/MAVENSDC/cdflib/pull/170. The error you get with the above code is now:
```python
Traceback (most recent call last):
  File "/Users/dstansby/github/cdflib/cdflib/cdfwrite.py", line 726, in write_var
    dataType = int(var_spec['Data_Type'])
ValueError: invalid literal for int() with base 10: 'CDF_EPOCH'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/Users/dstansby/github/cdflib/test.py", line 28, in <module>
    cdf.write_var(var_spec, var_data=var_data)
  File "/Users/dstansby/github/cdflib/cdflib/cdfwrite.py", line 31, in ensure_open
    return func(self, *args, **kwargs)
  File "/Users/dstansby/github/cdflib/cdflib/cdfwrite.py", line 731, in write_var
    raise ValueError('Missing/invalid required spec for creating variable.') from e
ValueError: Missing/invalid required spec for creating variable.
(cdflib) 🐊 dstansby@Davids-MBP cdflib % git checkout main
error: pathspec 'main' did not match any file(s) known to git
```

Which tells you there's something wrong with 'Data_Type', not an `int`.

**Comment by johncoxon** [comment]
Thanks for advancing this, @dstansby!
