### ISSUE TITLE
Error using `varattsget` with `to_np=False`

### ISSUE THREAD

**Issue by rweigel** [MAVENSDC/cdflib#177]
`cdflib 0.4.4`

```
import cdflib
cdffile = cdflib.CDF('ac_h0s_mfi_20230116000011_20230116000147.cdf') # File attached to bottom of issue page.
cdfGAttributes = cdffile.globalattsget();
cdfInfo  = cdffile.cdf_info()
variables = [*cdfInfo['rVariables'], *cdfInfo['zVariables']]

# Works
cdffile.varattsget('BGSEc', expand=False)

# Fails
cdffile.varattsget('BGSEc', expand=False, to_np=False)

```

```
Traceback (most recent call last):
  File "/Users/weigel/bug.py", line 7, in <module>
    cdffile.varattsget('BGSEc', expand=False, to_np=False)
  File "/Users/weigel/miniconda3/lib/python3.9/site-packages/cdflib/cdfread.py", line 705, in varattsget
    return self._read_varatts(vdr_info['variable_number'], zVar, expand, to_np=to_np)
  File "/Users/weigel/miniconda3/lib/python3.9/site-packages/cdflib/cdfread.py", line 1102, in _read_varatts
    aedr_info = self._read_aedr(byte_loc, to_np=to_np)
  File "/Users/weigel/miniconda3/lib/python3.9/site-packages/cdflib/cdfread.py", line 1279, in _read_aedr
    return self._read_aedr3(byte_loc, to_np)
  File "/Users/weigel/miniconda3/lib/python3.9/site-packages/cdflib/cdfread.py", line 1320, in _read_aedr3
    entry = self._convert_data(byte_stream, data_type, 1, 1, num_elements)
  File "/Users/weigel/miniconda3/lib/python3.9/site-packages/cdflib/cdfread.py", line 2300, in _convert_data
    return list(struct.unpack_from(form,
struct.error: unpack_from requires a buffer of at least 12 bytes for unpacking 12 bytes at offset 0 (actual buffer size is 4)
```

[ac_h0s_mfi_20230116000011_20230116000147.cdf.gz](https://github.com/MAVENSDC/cdflib/files/11458749/ac_h0s_mfi_20230116000011_20230116000147.cdf.gz)

**Comment by dstansby** [comment]
Thanks for reporting - in version 1.0.0 I've removed the to_np arguments, and cdflib returns arrays everywhere now, so I'll close this. Please do open more issues if you find anything else!
