### ISSUE TITLE
gzip issue

### ISSUE THREAD

**Issue by eyhl** [MAVENSDC/cdflib#31]
Hi there,

I have recently begun using cdflib, and it works great. However I get this error when I try to read in a certain variable in my .cdf called "Flags_B". Please see attached code. 
The .cdf can be found at: [https://github.com/eyhl/geomagpy](url)

```
import cdflib

path = "data/SW_OPER_MAGB_LR_1B_20140914T000000_20140914T235959_0405_MDR_MAG_LR.cdf"
cdf_file = cdflib.CDF(path)
cdf_file.varget("Flags_B")
```

Prodcuces the error:
```
Traceback (most recent call last):
  File "/Users/eyu/Google Drive/DTU/BSc_continued/0remake/geomagpy/dev_cdf_loader.py", line 18, in <module>
    cdf_file.varget("Flags_B")
  File "/anaconda3/envs/geomagpy/lib/python3.6/site-packages/cdflib/cdfread.py", line 545, in varget
    expand=expand, to_np=to_np)
  File "/anaconda3/envs/geomagpy/lib/python3.6/site-packages/cdflib/cdfread.py", line 2007, in _read_vardata
    startrec, endrec, to_np=to_np)
  File "/anaconda3/envs/geomagpy/lib/python3.6/site-packages/cdflib/cdfread.py", line 1653, in _read_vvrs
    var_block_data = self._read_vvr_block(vvr_offs[vvr_num])
  File "/anaconda3/envs/geomagpy/lib/python3.6/site-packages/cdflib/cdfread.py", line 2177, in _read_vvr_block
    return gzip.decompress(block[16:])
  File "/anaconda3/envs/geomagpy/lib/python3.6/gzip.py", line 532, in decompress
    return f.read()
  File "/anaconda3/envs/geomagpy/lib/python3.6/gzip.py", line 276, in read
    return self._buffer.read(size)
  File "/anaconda3/envs/geomagpy/lib/python3.6/gzip.py", line 463, in read
    if not self._read_gzip_header():
  File "/anaconda3/envs/geomagpy/lib/python3.6/gzip.py", line 411, in _read_gzip_header
    raise OSError('Not a gzipped file (%r)' % magic)
OSError: Not a gzipped file (b'\x7fA')
```

It seems to me that Flags_B is already decompressed but cdflib tries to decompress and it fails?

I am running python 3.6 on macOS High Sierra 10.13.6

Hope you can help out!
Best regards,
Eigil

**Comment by bryan-harter** [comment]
It looks like the way we were reading in compressed variables wasn't correct in certain situations, but I believe I just fixed it
