### ISSUE TITLE
cdflib-0.3.12 fails to decompress/read some CDFs

### ISSUE THREAD

**Issue by phansel** [MAVENSDC/cdflib#60]
Reading in certain data files with cdflib.CDF() fails with an error in the _read_cpr function. This has been confirmed on multiple installations and operating systems:

> >>> cdflib.CDF("mms1_dsp_fast_l2_swd_20150721_v0.4.0.cdf")
> Traceback (most recent call last):
>   File "<stdin>", line 1, in <module>
>   File "/home/user/.local/lib/python3.7/site-packages/cdflib/__init__.py", line 16, in CDF
>     return cdfread.CDF(path, validate=validate)
>   File "/home/user/.local/lib/python3.7/site-packages/cdflib/cdfread.py", line 78, in __init__
>     new_path = self._uncompress_file(path)
>   File "/home/user/.local/lib/python3.7/site-packages/cdflib/cdfread.py", line 714, in _uncompress_file
>     data_start, data_size, cType, _ = self._read_ccr(8)
>   File "/home/user/.local/lib/python3.7/site-packages/cdflib/cdfread.py", line 740, in _read_ccr
>     cType, cParams = self._read_cpr(cproffset)
>   File "/home/user/.local/lib/python3.7/site-packages/cdflib/cdfread.py", line 761, in _read_cpr
>     cpr = f.read(block_size-8)
> ValueError: read length must be non-negative or -1
> 

Example data file (fails):
[mms1_dsp_fast_l2_swd_20150721_v0.4.0.cdf.zip](https://github.com/MAVENSDC/cdflib/files/3346882/mms1_dsp_fast_l2_swd_20150721_v0.4.0.cdf.zip)

Example data file (succeeds):
[mms1_dsp_fast_l2_swd_20150720_v0.4.0.cdf.zip](https://github.com/MAVENSDC/cdflib/files/3346867/mms1_dsp_fast_l2_swd_20150720_v0.4.0.cdf.zip)

Both files are read with no issues by the NASA CDF library (and IDL).

**Comment by phansel** [comment]
It appears that the unreadable data file is missing the
